name: escultunas_application
description: Una aplicación movil para conocer las esculturas de Las Tunas.
publish_to: 'none'
version: 1.0.2

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.0
  carousel_slider: ^4.2.1
  sqflite:
  url_launcher: ^6.1.11
  async: ^2.9.0
  collection: ^1.16.0
  http: ^1.1.0
  http_plus: ^0.2.2
  path: ^1.8.2
  path_provider: ^2.0.7
  flutter_osm_plugin: ^0.60.4
  qr_flutter: ^4.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2


flutter:
  uses-material-design: true


  assets:
  - assets/images/
  - assets/logos/
